package:
    name: cobyla
    version: !!str {{ environ['PKG_VERSION'] }}

source:
    path: ../../contrib/cobyla

build:
    preserve_egg_dir: True

requirements:
    build:
        - python
        - setuptools
        - numpy ==1.7.1
        - libpython # [win]

    run:
        - python
        - numpy >=1.7.1
        - libpython # [win]
		

