package:
    name: bson
    version: !!str 0.3.3

source:
    git_url: https://github.com/martinkou/bson.git

requirements:
    build:
        - python
        - setuptools

    run:
        - python
