package:
    name: newsumt
    version: !!str 1.1.1

source:
    path: ../../contrib/newsumt

build:
    preserve_egg_dir: True

requirements:
    build:
        - python
        - setuptools
        - numpy ==1.7.1
        - libpython # [win]

    run:
        - python
        - numpy >=1.7.1
        - libpython # [win]
