package:
    name: openmdao.examples.nozzle_geometry_doe
    version: dev
    
source:
    path: ../../examples/openmdao.examples.nozzle_geometry_doe

build:
    preserve_egg_dir: True
        
requirements:
    build:
        - python
        - setuptools
        - openmdao.main
        - openmdao.lib
                
    run:
        - python
        - setuptools
        - openmdao.main
        - openmdao.lib
